### ISSUE TITLE
Support package_index.json

### ISSUE THREAD

**Issue by henrik1235** [cniweb/avr-netino#14]
Adding a package_index.json would make the installation of the AVR NET I/O board easier.

See:

https://github.com/arduino/Arduino/wiki/Arduino-IDE-1.6.x-package_index.json-format-specification
https://github.com/arduino/Arduino/wiki/Unofficial-list-of-3rd-party-boards-support-urls

**Comment by cniweb** [comment]
Good idea, can you tell me please help?
How would the contents of the file look like?

**Comment by henrik1235** [comment]
I added a package_index.json file by myself:
https://github.com/henrik1235/avr-netino/commit/478d50d6976f368aa723d78d6025d85813fd71e1

Was a bit try and error, but it seems to work.

**Comment by cniweb** [comment]
Hi @henrik1235 great work.
Can you create a PR, please?
Thanks!
